version: '2.2'

services:
  transfers:
    container_name: transfers
    build: ./local-environment
    volumes:
      - .:/var/www/app
      - ~/.ssh:/home/app/.ssh
      - ./local-environment/default.conf:/etc/nginx/conf.d/default.conf
      - ./local-environment/supervisor.conf:/etc/supervisord.conf
      - ./local-environment/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      transfers-network:
        ipv4_address: 192.168.33.161

networks:
  transfers-network:
    external:
      name: setup_rh-network
