# Alpine 3.9 using PHP 7.2

FROM alpine:3.9

RUN apk update && \
    apk add supervisor nginx php7 php7-fpm php7-mbstring php7-gd php7-dom php7-imap php7-curl \
    php7-pecl-memcached php7-pecl-redis php7-pdo_mysql php7-tokenizer php7-openssl php7-fileinfo \
    php7-pecl-xdebug php7-sockets php7-simplexml php7-xmlwriter php7-xml php7-sqlite3 php7-pdo_sqlite \
    php7-pecl-apcu php7-bcmath php7-bz2 php7-ctype php7-exif php7-ftp php7-gmp php7-intl php7-pcntl php7-posix php7-soap \
    php7-sodium php7-xmlreader php7-xmlrpc php7-zip php7-opcache \
    sqlite composer git openssh curl && \
    sed -i 's/expose_php = On/expose_php = Off/g' /etc/php7/php.ini && \
    sed -i 's/memory_limit = 128M/memory_limit = 4G/g' /etc/php7/php.ini && \
    sed -i 's/max_execution_time = 30/max_execution_time = 600/g' /etc/php7/php.ini && \
    mkdir -p /var/log/supervisor /run/nginx
